# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20170529_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
