# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('fecha_solicitado', models.DateField(auto_now_add=True)),
                ('hora_entregado', models.DateTimeField(blank=True, null=True)),
                ('paquetes', models.ManyToManyField(to='productos.Paquetes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('AL', 'Alcohol'), ('CM', 'Comida'), ('SN', 'Sonido'), ('MI', 'Miscelaneo')], max_length=2)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='productos.Productos'),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='productos',
            field=models.ManyToManyField(to='productos.Productos'),
        ),
    ]
