# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
